name: Deploy website
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Get cach Path
        id: dpn-cach-dir
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - name: caching-depn
        uses: actions/cache@v5
        with:
          path: ${{ steps.dpn-cach-dir.outputs.dir }}
          key: ${{ runner.os }}--node--${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.newid.outputs.script-file }}
    steps:
   
      - name: Get code
        uses: actions/checkout@v6
      - name: Get cach Path
        id: dpn-cach-dir
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - name: caching-depn
        uses: actions/cache@v5
        with:
          path: ${{ steps.dpn-cach-dir.outputs.dir }}
          key: ${{ runner.os }}--node--${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build website
        run: npm run build

      - name: Git File Name 
        id: newid
        run: find dist/assets/*.js -type f -printf "script-file=%f\n" >> $GITHUB_OUTPUT 
        
      - name: upload-artifact
        uses: actions/upload-artifact@v7
        with:
           name: dest-artifact
           path: |
             dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Git artifact
        uses: actions/download-artifact@v8
        with:
          name: dest-artifact
      - name: Deploy
        run: echo "Deploying..."
      - name: check download artifact 
        run: ls -l
      - name: Git outputs
        run: echo ${{ needs.build.outputs.script-file }}

